imgsite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('picture/', include('picture.urls'))
]

picture/urls.py
from . import views
from django.urls import path

app_name = 'picture'
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:page>', views.index, name='index'),
    path('tag/<str:tag_name>', views.tag, name="tag"),
    path('tag/<str:tag_name>/<int:page>', views.tag, name='tag'),
    path('search/', views.search_post, name='search'),
    path('search/<str:search_word>', views.search, name='search'),
    path('search/<str:search_word>/<int:page>', views.search, name='search'),
    path('create_post/', views.topic_create, name='create_post'),
    path('detail_post/<int:pk>/', views.TopicAndCommentView.as_view(), name='detail_post')
]

picture/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone


class Post(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    upload_date = models.DateTimeField()

    def publish(self):
        self.published_date = timezone.now()

        self.save()

    def __str__(self):
        return self.title


class PostTagName(models.Model):
    name = models.CharField(max_length=200, default="")

    def __str__(self):
        return self.name


class PostTagList(models.Model):
    content = models.ForeignKey(Post, on_delete=models.CASCADE)
    tag = models.ForeignKey(PostTagName, on_delete=models.CASCADE)


class PostComment(models.Model):
    id = models.BigAutoField(
        primary_key=True,
    )
    no = models.IntegerField(
        default=0,
    )
    user_name = models.CharField(
        max_length=30,
        null=True,
        blank=False,
    )
    topic = models.ForeignKey(
        Post,
        on_delete=models.PROTECT,
    )
    message = models.TextField(
        max_length=1000, default=""
    )
    pub_flg = models.BooleanField(
        default=True,
    )
    created = models.DateTimeField(
        auto_now_add=True,
    )

    def __str__(self):
        return '{}-{}'.format(self.topic.id, self.no)

class VoteManager(models.Manager):
    def create_vote(self, ip_address, comment_id):
        vote = self.model(
            ip_address=ip_address,
            comment_id = comment_id
        )
        try:
            vote.save()
        except:
            return False

        return True

class Vote(models.Model):
    comment = models.ForeignKey(
        PostComment,
        on_delete=models.CASCADE,
        null=True,
    )
    ip_address = models.CharField(
        'IPアドレス',
        max_length=50,
    )

    objects = VoteManager()

    def __str__(self):
        return '{}-{}'.format(self.comment.topic.title, self.comment.no)




# Create your models here.

picture/forms.py
from django.forms import ModelForm
from . models import Post, PostComment
from django import forms


class PostForm(forms.Form):
    title = forms.CharField(
        label='タイトル',
        max_length=255,
        required=True,
    )

    tag = forms.CharField(
        label='タグ',
        max_length=200,
        required=True,
    )
    text = forms.CharField(
        label='説明文',
        widget=forms.Textarea,
        required=True,
    )


class CommentModelForm(forms.ModelForm):
    class Meta:
        model = PostComment
        fields = [
            'user_name',
            'message',
        ]

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super().__init__(*args, **kwargs)
        self.fields['user_name'].widget.attrs['value'] = '名無し'

picture/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import Post, PostTagList, PostTagName, PostComment
from django.db.models import Count,Q
from django.urls import reverse,reverse_lazy
from . forms import PostForm, CommentModelForm
from django.utils import timezone
from django import forms
from django.views.generic import FormView



def index(request, page=0):
    max_page = Post.objects.count() // 10
    return construct_page(request, PostTagList.objects.values('content_id'), Post.objects.order_by('-upload_date')[page*10:(page+1)*10].values(), page, max_page, 'picture:index')


def construct_page(request, all_content_ids, page_contents, current_page, max_page, url_type, url_word=''):
    contents = []
    for item in page_contents:
        tmp_dict = item
        tmp_dict.update({'tags': PostTagList.objects.filter(content_id=item['id']).select_related('tag')})
        contents.append(tmp_dict)


    tag_cnt = PostTagList.objects.filter(content__in=all_content_ids).values('tag').annotate(tag_count=Count('tag')).order_by('-tag_count')[:15]
    tag_names = [PostTagName.objects.filter(id = item.get('tag'))[0] for item in tag_cnt]
    tags = [{'name': tag_names[i].name, 'count': tag_cnt[i]["tag_count"]} for i in range(len(tag_names))]


    page_list = [{'num':x, 'valid':0 <= x and x <= max_page} for x in range(current_page-5, current_page+4)]


    return render(request, 'picture/index.html', {'tags': tags, 'contents': contents, 'page':{'type':url_type, 'word': url_word, 'current': current_page, 'max': max_page, 'list': page_list}})


def tag(request, tag_name, page=0):

    tag_id = PostTagName.objects.filter(name=tag_name).get().id
    filtered_list = PostTagList.objects.select_related('content').filter(tag=tag_id).order_by('-content__upload_date')

    max_page = filtered_list.count() // 10

    content_list = filtered_list[page*10:(page+1)*10]
    contents = [{'id':item.content.id, 'title':item.content.title, 'text':item.content.text, 'upload_date':item.content.upload_date} for item in content_list]

    return construct_page(request, PostTagList.objects.values('content_id'), contents, page, max_page, 'picture:tag', tag_name)


def search(request, search_word, page=0):
    filtered_list = Post.objects.filter(Q(title__contains=search_word) | Q(text__icontains=search_word)).order_by('-upload_date')
    max_page = filtered_list.count() // 10

    content_list = filtered_list[page * 10:(page + 1) * 10]
    contents = [{'id': item.id, 'title': item.title, 'text':Post.objects.filter(id=item.id)[0].text, 'upload_date':item.upload_date} for item in content_list]

    return construct_page(request, PostTagList.objects.values('content_id'), contents, page, max_page, 'picture:search', search_word)


def search_post(request):
    d = {
        'Search': request.POST.get('Search')
    }
    if d['Search'] != "":
        return HttpResponseRedirect(reverse('picture:search', args=(request.POST['Search'],)))

    return HttpResponseRedirect(reverse('picture:index'))


def topic_create(request):
    template_name = 'picture/create_post.html'
    ctx = {}
    if request.method == 'GET':
        ctx['form'] = PostForm()
        return render(request, template_name, ctx)

    if request.method == 'POST':
        post_form = PostForm(request.POST)
        if post_form.is_valid():
            post = Post()
            #post_tag = PostTagName()
            #post_tag_list = PostTagList()
            cleaned_data = post_form.cleaned_data
            post.title = cleaned_data['title']
            post.text = cleaned_data['text']
            post.upload_date = timezone.now()
            all_tags = request.POST["tag"]
            all_tags_split = str(all_tags).split("#")
            del all_tags_split[0]
            post.save()
            for t in all_tags_split:
                tags = PostTagName.objects.filter(name=t)
                if len(tags) == 0:
                   PostTagName.objects.create(name=t)
                   PostTagList.objects.create(content=post, tag=PostTagName.objects.filter(name=t).get())
                else:
                   PostTagList.objects.create(content=post, tag=PostTagName.objects.filter(name=t).get())

        return redirect(reverse_lazy('picture:index'))


class TopicAndCommentView(FormView):
    template_name = 'picture/detail_post.html'
    form_class = CommentModelForm

    def form_valid(self, form):
         comment = form.save(commit=False)
         comment.topic = Post.objects.get(id=self.kwargs['pk'])
         comment.no = PostComment.objects.filter(topic=self.kwargs['pk']).count() + 1
         comment.save()
         return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('picture:detail_post', kwargs={'pk': self.kwargs['pk']})

    def get_context_data(self):
        ctx = super().get_context_data()

        tag_cnt = PostTagList.objects.filter(content__in=PostTagList.objects.values('content_id')).values('tag').annotate(tag_count=Count('tag')).order_by('-tag_count')[:15]
        tag_names = [PostTagName.objects.filter(id=item.get('tag'))[0] for item in tag_cnt]
        tags = [{'name': tag_names[i].name, 'count': tag_cnt[i]["tag_count"]} for i in range(len(tag_names))]
        ctx['post_tags'] = PostTagList.objects.filter(content_id=self.kwargs['pk'])
        ctx['tags'] = tags
        ctx['topic'] = Post.objects.get(id=self.kwargs['pk'])
        ctx['comment_list'] = PostComment.objects.filter(topic_id=self.kwargs['pk']).order_by('no')
        return ctx



# Create your views here.

picture/templates/picture/base.html
<!DOCTYPE html>
{% bootstrap_css %}
<html lang="ja">
<head>
  <meta charset="UTF-8">

  <title>{% block title %}Postit{% endblock %}</title>
{% load static %}
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+1p|Monoton&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'picture/main.css' %}">

{% block header %}{% endblock %}
</head>
<body>
<div style="position:relative; height:80px; font-family:'M PLUS 1p';">
<nav class="navbar  navbar-light navbar-expand-lg navbar-fixed-top border-bottom border-primary shadow" style="background-color: #99CCFF;" >
    <a class="navbar-brand" href="{% url 'picture:index' %}"><p style="font-family: 'Monoton';">Postit</p></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    </ul>
    <div class="mx-auto" style="width: 685px;">
    <form class="form-inline" action="{% url 'picture:search' %}" method="post">
        {% csrf_token %}
      <div class="input-group position-fixed">
      <input class="form-control" type="text" placeholder="キーワード検索" aria-label="Search" name="Search" style="width: 500px;">
          <div class="input-group-append">
          <button class="btn btn-secondary" type="submit"><svg class="bi bi-search" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 011.415 0l3.85 3.85a1 1 0 01-1.414 1.415l-3.85-3.85a1 1 0 010-1.415z" clip-rule="evenodd"/>
  <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 100-11 5.5 5.5 0 000 11zM13 6.5a6.5 6.5 0 11-13 0 6.5 6.5 0 0113 0z" clip-rule="evenodd"/>
  </svg></button>
          </div>
      </div>
    </form>
    </div>
  </div>
</nav>
</div>

<div class="float-left position-fixed" style="width: 20rem; margin-left: 17px; font-family:'M PLUS 1p';">
  <a class="btn btn-primary btn btn-block shadow" href="{% url 'picture:create_post' %}" role="button" style="font-family:'M PLUS 1p';">
  スレッド作成<svg class="bi bi-pencil-square" width="1em" height="0.9em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M15.502 1.94a.5.5 0 010 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 01.707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 00-.121.196l-.805 2.414a.25.25 0 00.316.316l2.414-.805a.5.5 0 00.196-.12l6.813-6.814z"/>
  <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 002.5 15h11a1.5 1.5 0 001.5-1.5v-6a.5.5 0 00-1 0v6a.5.5 0 01-.5.5h-11a.5.5 0 01-.5-.5v-11a.5.5 0 01.5-.5H9a.5.5 0 000-1H2.5A1.5 1.5 0 001 2.5v11z" clip-rule="evenodd"/>
  </svg></a>
  <br>
  <h4 style="font-family:'M PLUS 1p';"><svg class="bi bi-tag" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M.5 2A1.5 1.5 0 012 .5h4.586a1.5 1.5 0 011.06.44l7 7a1.5 1.5 0 010 2.12l-4.585 4.586a1.5 1.5 0 01-2.122 0l-7-7A1.5 1.5 0 01.5 6.586V2zM2 1.5a.5.5 0 00-.5.5v4.586a.5.5 0 00.146.353l7 7a.5.5 0 00.708 0l4.585-4.585a.5.5 0 000-.708l-7-7a.5.5 0 00-.353-.146H2z" clip-rule="evenodd"/>
  <path fill-rule="evenodd" d="M2.5 4.5a2 2 0 114 0 2 2 0 01-4 0zm2-1a1 1 0 100 2 1 1 0 000-2z" clip-rule="evenodd"/>
  </svg> 関連タグ<small>(登録数順)</small></h4>
  <ul class="list-group" style="max-width: 240px;">
  {% for item in tags %}
    <li class="list-group-item shadow"><a href="{% url 'picture:tag' item.name %}">{{ item.name }}</a> ({{ item.count }})</li>
  {% endfor %}
  </ul>
</div>
{% block main %}
{% endblock %}
</body>
</html>

picture/templates/picture/confirm_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

picture/templates/picture/create_post.html
<!DOCTYPE html>
{% bootstrap_css %}
<html lang="ja">
<head>
  <meta charset="UTF-8">

  <title>{% block title %}Postit{% endblock %}</title>
{% load static %}
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" type="text/css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+1p|Monoton&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'picture/main.css' %}">

{% load widget_tweaks %}
</head>
<body>
<html>
<head>
    <title>スレッド作成ページ</title>
</head>
<body>
<div style="position:relative; height:80px;">
<nav class="navbar  navbar-light navbar-expand-lg navbar-fixed-top border-bottom border-primary shadow" style="background-color: #99CCFF;" >
    <a class="navbar-brand" href="{% url 'picture:index' %}"><p style="font-family: 'Monoton';">Postit</p></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    </ul>
    <div class="mx-auto" style="width: 700px;">
    <form class="form-inline" action="{% url 'picture:search' %}" method="post">
        {% csrf_token %}
      <div class="input-group">
      <input class="form-control form-control-lg" type="text" placeholder="キーワード検索" aria-label="Search" name="Search" style="width: 500px;">
          <div class="input-group-append">
          <button class="btn btn-secondary" type="submit">検索</button>
          </div>
      </div>
    </form>
    </div>
  </div>
</nav>
</div>
<link rel="stylesheet" type="text/css" href="{% static 'picture/main.css' %}">
<div class="content mx-auto" style="width: 145rem; font-family:'M PLUS 1p';">
    <div class="header col-md-offset-3"><h3>スレッド作成</h3></div>
    <div class="content">
          <form class="" action="{% url 'picture:create_post' %}" method="POST">
              {% csrf_token %}
              <div class="form-group">
               <div class="col-md-6 col-md-offset-3">{{form.title.label_tag}}{{form.title|add_class:"form-control"}}</div>
              </div>
              <div class="form-group">
                  <div class="col-md-6 col-md-offset-3"><p>{{form.tag.label_tag}}(例: #スポーツ#野球#アウトドア)</p>{{form.tag|add_class:"form-control"}}</div>
              </div>
              <div class="form-group">
               <div class="col-md-6 col-md-offset-3">{{form.text.label_tag}}{{form.text|add_class:"form-control"}}</div>
              </div>
                  {% for error in field.errors %}
                  <p style="color: red;">{{error}}</p>
                  {% endfor %}
              <div class="col-md-1 col-md-offset-8">
              <button type="submit" class="btn btn-success">作成</button>
              </div>
          </form>
    </div>
</div>
</body>
</html>

picture/templates/picture/detail_post.html
{% extends "picture/base.html" %}

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% load static %}
{% load widget_tweaks %}
{% load postfilters %}
{% block main %}
<div class="col-md-9  col-md-offset-2" style="font-family:'M PLUS 1p';">
            <div class="card">
                <div class="card-header shadow"><h3 style="text-align: center;"><svg class="bi bi-chat-square-dots" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M14 1H2a1 1 0 00-1 1v8a1 1 0 001 1h2.5a2 2 0 011.6.8L8 14.333 9.9 11.8a2 2 0 011.6-.8H14a1 1 0 001-1V2a1 1 0 00-1-1zM2 0a2 2 0 00-2 2v8a2 2 0 002 2h2.5a1 1 0 01.8.4l1.9 2.533a1 1 0 001.6 0l1.9-2.533a1 1 0 01.8-.4H14a2 2 0 002-2V2a2 2 0 00-2-2H2z" clip-rule="evenodd"/>
                <path d="M5 6a1 1 0 11-2 0 1 1 0 012 0zm4 0a1 1 0 11-2 0 1 1 0 012 0zm4 0a1 1 0 11-2 0 1 1 0 012 0z"/>
                </svg>{{topic.title}}</h3></div>
                <p class="card-body" style="text-align: center; font-size: normal;">{{topic.text| comment_filter | safe}}({{topic.upload_date}}){% for tag in post_tags %}<a href="{% url 'picture:tag' tag.tag.name %}">#{{tag.tag.name}}</a>{% endfor %}</p>
            </div>
        <!--コメント表示-->
            <div class="card shadow">
            {% if comment_list %}
            {% for comment in comment_list %}
            <li class="list-group-item shadow">
                <p style="font-size: large;">{{comment.no}}. {{comment.user_name}}({{comment.created}})<br>{{comment.message | comment_filter | safe}}</p>
            </li>
            {% endfor %}
            {% else %}
            <div class="card-body"><p style="font-size: large; text-align: center;">まだコメントはありません</p></div>
            {% endif %}
        </div>
        <!--//コメント表示-->
        <!--コメント投稿-->
                <form class="form" action="" method="POST">
                <div class="card">
                <div class="card-header shadow">
                <h4><svg class="bi bi-pencil" width="1em" height="1em" viewBox="0 1 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M11.293 1.293a1 1 0 011.414 0l2 2a1 1 0 010 1.414l-9 9a1 1 0 01-.39.242l-3 1a1 1 0 01-1.266-1.265l1-3a1 1 0 01.242-.391l9-9zM12 2l2 2-9 9-3 1 1-3 9-9z" clip-rule="evenodd"/>
                <path fill-rule="evenodd" d="M12.146 6.354l-2.5-2.5.708-.708 2.5 2.5-.707.708zM3 10v.5a.5.5 0 00.5.5H4v.5a.5.5 0 00.5.5H5v.5a.5.5 0 00.5.5H6v-1.5a.5.5 0 00-.5-.5H5v-.5a.5.5 0 00-.5-.5H3z" clip-rule="evenodd"/>
                </svg> コメント投稿</h4>
                </div>
                </div>
                <div class="card shadow border rounded">
                {% csrf_token %}
                <div class="form-group shadow card-header">
                <div class="">{{form.user_name.label_tag}}{{form.user_name|add_class:"form-control"}}</div>
                </div>
                <div class="form-group border-top shadow card-header">
                <div class="">{{form.message.label_tag}}{{form.message|add_class:"form-control"}}</div>
                </div>
                </div>
                <button class="btn btn-success shadow" type="submit">コメント投稿</button>
                </form>
        <!--//コメント投稿-->
    </div>

</div>
</div>
{% endblock %}